config/routes.rb
Bookgame::Application.routes.draw do

  devise_for :users
  
  resources :users

  resources :books do
   post :complete, on: :member
   post :uncomplete, on: :member
   post :publish, on: :member
   post :unpublish, on: :member
   resources :chapters do
    post :sort, on: :collection
    post :complete, on: :member
    post :uncomplete, on: :member
   end
  end

  match 'user/:id/view' => 'users#view', :via => :get, :as => :user_view

  match 'book/:book_id/chapters/map' => 'chapters#map', :via => :get, :as => :book_chapters_map
  match 'book/:id/view' => 'books#view', :via => :get, :as => :book_view
  match 'book/:id/download' => 'books#download', :via => :get, :as => :book_download

  root 'welcome#index'

end

app/models/user.rb
class User < ActiveRecord::Base
  has_and_belongs_to_many :books

  acts_as_commentable
  
  enum role: [:user, :vip, :admin]

  after_initialize :set_default_role, :if => :new_record?

  def set_default_role
    self.role ||= :user
  end

  has_attached_file :picture, :styles => { :hi_res => "1200x1200", :large => "600x600>", :medium => "200x200>", :thumb => "100x100>" }, :default_url => "/images/:style/missing.png"
    validates_attachment_content_type :picture, :content_type => /\Aimage\/.*\Z/
  
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :authenticate_user!, except: :view
  after_action :verify_authorized, except: :view

  def index
    @users = User.where("id != ?", current_user.id)
    authorize User
  end

  def view
    @user = User.find(params[:id])
  end

  def destroy
    user = User.find(params[:id])
    authorize user
    user.destroy
    redirect_to users_path, :notice => "User deleted."
  end

  private

  def secure_params
    params.require(:user).permit(:role, :picture )
  end

end

app/views/users/index.html.erb
<h1>Listing users</h1>

<div class="container books">
  <div class="row">
    <% @users.each do |user| %>
      <div class="user span4">
        <h3><%= link_to user.email, edit_user_path(user) %></h3>
        <p class="image"><%= #link_to image_tag(user.cover.url(:medium)), edit_user_path(user) 
        %></p>
        <ul>
          <li><%= link_to 'View user Public Page', user_view_path(user) %></li>
          <li><%= link_to "Edit user Details", edit_user_path(user) %></li>
          <li><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></li>
        </ul>
      </div>
    <% end %>
  </div>
</div>

app/views/users/view.html.erb
<p>
  <strong>Email:</strong>
  <%= @user.email %>
</p>
<p>
<%= image_tag @user.picture.url(:medium) %>
</p>

<h2>Books</h2>
<ul>
<% @user.books.publishable.each{|book| %>
	<li><%= link_to book.title, book_view_path(book) %></li>
<%	} %>
</ul>
	


<hr />
<h2>Comments</h2>
<% @user.comments.each{|comment| %>
	<h3><%= comment.title %></h3>
<%	} %>

<%= link_to 'Back', books_path %>