config/routes.rb
Bookgame::Application.routes.draw do

  devise_for :users
  
  resources :users

  resources :books do
   post :complete, on: :member
   post :uncomplete, on: :member
   post :publish, on: :member
   post :unpublish, on: :member
   resources :chapters do
    post :sort, on: :collection
    post :complete, on: :member
    post :uncomplete, on: :member
   end
  end

  match 'user/:id/view' => 'users#view', :via => :get, :as => :user_view

  match 'book/:book_id/chapters/map' => 'chapters#map', :via => :get, :as => :book_chapters_map
  match 'book/:id/view' => 'books#view', :via => :get, :as => :book_view
  match 'book/:id/download' => 'books#download', :via => :get, :as => :book_download

  root 'welcome#index'

end

app/models/book.rb
class Book < ActiveRecord::Base
	
	include Completable

	validates :title, :presence => true

	has_paper_trail

	acts_as_commentable

	has_and_belongs_to_many :users
	has_many :chapters

	accepts_nested_attributes_for :chapters

	has_attached_file :cover, :styles => { :hi_res => "1200x1200", :large => "600x600>", :medium => "200x200>", :thumb => "100x100>" }, :default_url => "/images/:style/missing.png"
  	validates_attachment_content_type :cover, :content_type => /\Aimage\/.*\Z/

  	scope :publishable, -> { where(completed: true, publishable: true) }
  	
  	scope :owned_by, -> (user=nil) { joins(:users).where(users:{id: user.id}) }
  	scope :not_owned_by, -> (user=nil) { all - owned_by(user) }

	def completable?
		!chapters.map{|chapter|
			chapter.completable?
		}.include?(false) 
	end

	def complete!
		if completable?
			chapters.each{|chapter|
				chapter.complete!
			} 
			self.completed = true
			save! 
		end
	end

	def publish!
		self.publishable = true
		save!
	end

	def unpublish!
		self.publishable = false
		save!
	end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :set_book, only: [:show, :edit, :update, :destroy, :publish, :unpublish, :complete, :uncomplete]
  before_filter :authenticate_user!, :except => [:view, :download]

  # GET /books
  # GET /books.json
  def index
    @books = policy_scope(Book)
    @other_books = Book.publishable - @books
  end

  # GET /books/1
  # GET /books/1.json
  def show
  end

  def view
    @book = Book.find(params[:id])
    @comments = @book.comments.recent.limit(10).all
  end

  def download
    @book = Book.find(params[:id])
    @chapters = @book.chapters.by_print_order
    
    respond_to do |format|
      format.html
      format.pdf do
        render :pdf => "#{@book.title}",
               
               :layout                         => 'pdf.html.haml',
               #:cover                          => "",
               :page_size                      => "A5",
               :font_name                      => "courier",
               :header                         => { :font_size => 8, :center => @book.title},
               :footer                         => { :center => '[page] of [topage]', :font_size => 8},
               :disposition                    => 'attachment'
      end
    end
  end

  # GET /books/new
  def new
    @book = Book.new
  end

  # GET /books/1/edit
  def edit
  end

  # POST /books
  # POST /books.json
  def create
    @book = Book.new(book_params)
    @book.users = [current_user]

    respond_to do |format|
      if @book.save
        format.html { redirect_to book_url(@book), notice: 'Book was successfully created.' }
        format.json { render action: 'index', status: :created, location: book_url(@book) }
      else
        format.html { render action: 'new' }
        format.json { render json: @book.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /chapter/1
  # PATCH/PUT /chapter/1.json
  def publish
    respond_to do |format|
      if @book.publish!
        format.html { redirect_to edit_book_path(@book), notice: 'Book successfully updated.' }
        format.json { head :no_content }
      else
        format.html { redirect_to edit_book_path(@book), alert: "Book is not publishable. Try to set all chapters as completed and then try again" }
        format.json { render json: @chapter.errors, status: :unprocessable_entity }
      end
    end
  end

  def unpublish
    respond_to do |format|
      if @book.unpublish!
        format.html { redirect_to edit_book_path(@book), notice: 'Book successfully updated.' }
        format.json { head :no_content }
      else
        format.html { redirect_to edit_book_path(@book), alert: "Book is not unpublishable." }
        format.json { render json: @chapter.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /chapter/1
  # PATCH/PUT /chapter/1.json
  def complete
    respond_to do |format|
      if @book.complete!
        format.html { redirect_to edit_book_url(@book), notice: 'Book was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { redirect_to edit_book_url(@book), alert: "Book was not completable. Check for the presence of #{LINK_REMOVED_TEXT} in the text" }
        format.json { render json: @book.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /chapter/1
  # PATCH/PUT /chapter/1.json
  def uncomplete
    respond_to do |format|
      if @book.uncomplete!
        format.html { redirect_to edit_book_url(@book), notice: 'Book was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @book.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /books/1
  # PATCH/PUT /books/1.json
  def update
    respond_to do |format|
      if @book.update(book_params)
        format.html { redirect_to book_url(@book), notice: 'Book was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @book.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /books/1
  # DELETE /books/1.json
  def destroy
    @book.destroy
    respond_to do |format|
      format.html { redirect_to books_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_book
      @book = Book.find(params[:id])
      authorize @book
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def book_params
      params.require(:book).permit(:title, :introtext, :page_format, :font_name, :font_google, :font_google_name, :credits,  :cover,:user_id)
    end
end

app/helpers/books_helper.rb
module BooksHelper
end

app/views/books/_form.html.haml
= form_for(@book, :html => { :multipart => true, :role => "form", :class => "form-horizontal" }) do |f|
 - if @book.errors.any?
  #error_explanation
   %h2
    {pluralize(@book.errors.count, "error")} prohibited this book from being saved:
    %ul
     - @book.errors.full_messages.each do |msg|
      li= msg

 .field.form-group
  = f.label :title, :class => "col-sm-2 control-label"
  .col-sm-10
   = f.text_field :title, :class => "form-control"

 .field.form-group
  = f.label :cover, :class => "col-sm-2 control-label"
  .col-sm-10
   = f.file_field :cover

 .field.form-group
  = f.label :introtext, :class => "col-sm-2 control-label"
  .col-sm-10
   = f.text_area :introtext, :class => "form-control redactor-intro", :rows => 40, :cols => 120

 .field.form-group
  = f.label :font_name, :class => "col-sm-2 control-label"
  .col-sm-10
   = f.text_field :font_name, :class => "form-control"

 .field.form-group
  = f.label :font_google, :class => "col-sm-2 control-label"
  .col-sm-10
   = f.check_box :font_google, :class => "form-control switch"

 .field.form-group
  = f.label :font_google_name, :class => "col-sm-2 control-label"
  .col-sm-10
   = f.text_field :font_google_name, :class => "form-control"

 .field.form-group
  = f.label :page_format, :class => "col-sm-2 control-label"
  .col-sm-10
   = f.select(:page_format, ["a4", "a5"], :include_blank => true, :class => "form-control")

 .field.form-group
  = f.label :credits, :class => "col-sm-2 control-label"
  .col-sm-10
   = f.text_area :credits, :class => "form-control redactor-intro", :rows => 40, :cols => 120

 .actions.form.group
  - if @book.completed?
   = link_to "Mark as Not Completed", uncomplete_book_path(@book), method: :post, data: { confirm: 'Are you sure?' },:class => 'btn btn-default'
   - unless @book.publishable?
    = link_to "Publish!", publish_book_path(@book), method: :post, data: { confirm: 'Are you sure?' },:class => 'btn btn-default'
   - else
    = link_to "Unpublish!", unpublish_book_path(@book), method: :post, data: { confirm: 'Are you sure?' },:class => 'btn btn-default'
  - else
   .alert.alert-success
    %p If you want to publish your book, make sure all chapters are marked as Completed

  - unless @book.new_record? || @book.completed
   = link_to "Mark As Completed", complete_book_path(@book), method: :post, data: { confirm: 'Are you sure?' }, :class => 'btn btn-default'

  - unless @book.new_record? 
   = link_to "List of Chapters", book_chapters_path(@book), :class => "btn btn-default"
  = f.submit class: 'btn btn-primary'

app/views/books/download.html.haml
%h1= @book.title
= image_tag @book.cover.url(:medium)
- @chapters.each_with_index do |chapter,index|
 %hr 
 %h4
  %a{:name => "#{chapter.id}"}
   Chapter #{index}
 %h2= chapter.title 
 #{shortcode_to_link(chapter, :fulltext, @chapters.map{|i| i.id})}

app/views/books/download.pdf.haml
= content_for :stylesheets do
 %style{:type => "text/css", :media =>:print}
  @import url(http://fonts.googleapis.com/css?family=@book.font_name);
  *{font-family:@book.font_name;}

%h1= @book.title
- @chapters.each_with_index do |chapter,index|
 %hr 
 %h4
  %a{:name => "#{chapter.id}"}
   Chapter #{index}
 %h2= chapter.title 
 #{shortcode_to_link(chapter, :fulltext, @chapters.map{|i| i.id})}

app/views/books/edit.html.haml
%h1 Editing book
= render 'form'
= link_to 'Back', books_path, :class => "btn btn-default"

app/views/books/index.html.haml
.container.books
 .row
  .book-list{:class => "col-md-" + (@other_books.empty? ? "12" : "8")}
   .widget-header
    %i.icon-list-alt
    %h3 Your Books

   .widget-content
    .actions
     = link_to "<span class=\"glyphicon glyphicon-plus\"></span>".html_safe, new_book_path

    - @books.each do |book|
     .book{:class => ("success" if book.completed)}
      %h3.title
       = link_to book.title, edit_book_path(book)
      %p.image= link_to image_tag(book.cover.url(:medium)), edit_book_path(book)
      %ul
       %li= link_to "<span class=\"glyphicon glyphicon-eye-open\"></span>".html_safe, book_view_path(book)
       %li= link_to "<span class=\"glyphicon glyphicon-download-alt\"></span>".html_safe, book_download_path(book,  {:format => "pdf"})
       %li= link_to "<span class=\"glyphicon glyphicon-edit\"></span>".html_safe, edit_book_path(book)
       %li= link_to "<span class=\"glyphicon glyphicon-tasks\"></span>".html_safe, book_chapters_path(book)
       %li= link_to "<span class=\"glyphicon glyphicon-map-marker\"></span>".html_safe, book_chapters_map_path(book), 'data-popup' => true
       %li= link_to "<span class=\"glyphicon glyphicon-trash\"></span>".html_safe, book, method: :delete, data: { confirm: 'Are you sure?' }

  = unless @other_books.empty?
   .col-md-4.otherbook-list
    .widget-header
     %i.icon-list-alt
     %h3 Books from your neighbours
    .widget-content
     - @other_books.each do |book|
      .book
       %h3.title= link_to book.title, book_view_path(book)
       %p.image= link_to image_tag(book.cover.url(:thumb)), book_view_path(book)

app/views/books/new.html.haml
%h1 New book
= render 'form'
= link_to 'Back', books_path, :class => "btn btn-default"

app/views/books/show.html.haml
%p#notice= notice
.book
 %p
  %strong Title:
  = @book.title

 %p
  = image_tag @book.cover.url(:medium)

 %ul
  %li= link_to "<span class=\"glyphicon glyphicon-download-alt\"></span>".html_safe, book_download_path(@book,  {:format => "pdf"})

%hr
%h2 Comments
= @book.comments.each do |comment|
 %h3= comment.title
%hr
= link_to 'Edit', edit_book_path(@book), :class => "btn btn-default"
= link_to 'Back', books_path, :class => "btn btn-default"

app/views/books/view.html.haml
%p#notice= notice
%p
 %strong Title:
 = @book.title

%p
 = image_tag @book.cover.url(:medium)

%ul
 %li= link_to 'Download Book in pdf', book_download_path(@book, {:format => "pdf"})

%hr
%h2 Comments
= @book.comments.each{|comment|
 %h3= comment.title

= link_to 'Back', books_path, :class => "btn btn-default"