config/routes.rb
Bookgame::Application.routes.draw do

  devise_for :users
  
  resources :users

  resources :books do
   post :complete, on: :member
   post :uncomplete, on: :member
   post :publish, on: :member
   post :unpublish, on: :member
   resources :chapters do
    post :sort, on: :collection
    post :complete, on: :member
    post :uncomplete, on: :member
   end
  end

  match 'user/:id/view' => 'users#view', :via => :get, :as => :user_view

  match 'book/:book_id/chapters/map' => 'chapters#map', :via => :get, :as => :book_chapters_map
  match 'book/:id/view' => 'books#view', :via => :get, :as => :book_view
  match 'book/:id/download' => 'books#download', :via => :get, :as => :book_download

  root 'welcome#index'

end

app/models/chapter.rb
class Chapter < ActiveRecord::Base

	include Completable
	
	has_paper_trail

	belongs_to :book

	acts_as_list scope: :book

	validates :title, :presence => true

	has_many :parent_chapters, :foreign_key => 'chapter_id', :class_name => 'Chaptership'
	has_many :child_chapters, :foreign_key => 'parent_id', :class_name => 'Chaptership'

	has_many :parents, :through => :parent_chapters, :source => :parent
	has_many :children, :through => :child_chapters, :source => :chapter

	accepts_nested_attributes_for :parent_chapters, :allow_destroy => false

	after_save :set_chapter_relations, :set_beginning, :set_ending

	scope :by_print_order, -> { order(:beginning).reverse_order}
	scope :by_order, -> { order(:position)}

    def ending_or_death?
    	ending? || death?
	end
	
	def completable?
		fulltext.scan(/#{LINK_REMOVED_TEXT}/).flatten.empty?
	end

	private

	def set_chapter_relations
		chapters_linked = fulltext.scan(/\[#{LINK_REPLACEMENT_TEXT} (\w*)\]/).flatten.uniq
		child_chapters.each {|c| c.destroy}
		unless chapters_linked.empty?
			chapters_linked.map do |child_chapter|
			  chapter = Chapter.find_by_id(child_chapter)
			  if chapter && chapter.book == self.book && !ending_or_death?
			    child_chapters.create!(:parent => self, :chapter => chapter)
			  else
			    field = fulltext.gsub(/\[#{LINK_REPLACEMENT_TEXT} #{Regexp.quote(child_chapter)}\]/, "#{LINK_REMOVED_TEXT}")
			    self.update_column(:fulltext, field)
			  end
			end
		end
    end

    def set_beginning
		if parents.empty?
			self.update_column(:beginning, true)
		else
			self.update_column(:beginning, false)
		end
    	unless children.empty?
			children.each do |chapter|
				chapter.update_column(:beginning, false)
			end
		end
	end
    def set_ending
    	if death?
			self.update_column(:ending, true)
		end
	end
end

app/controllers/chapters_controller.rb
class ChaptersController < ApplicationController
  before_action :set_chapter, only: [:show, :edit, :update, :destroy, :complete, :uncomplete]
  before_action :set_book, except: :map
  before_filter :authenticate_user!

  # GET /chapters
  # GET /chapters.json
  def index
    all_chapters
  end

  # GET /chapters/1
  # GET /chapters/1.json
  def show
  end

  def map
    @book = Book.find(params[:book_id])
    @chapters = policy_scope(@book.chapters)
    render layout: 'headless'
  end

  # GET /chapters/new
  def new
    @chapter = Chapter.new
    @chapter.book = @book
  end

  # GET /chapters/1/edit
  def edit
  end

  # POST /chapters
  # POST /chapters.json
  def create
    @chapter = Chapter.new(chapter_params)

    respond_to do |format|
      if @chapter.save
        format.html { redirect_to book_chapter_path(@book, @chapter), notice: 'Chapter was successfully created.' }
        format.json { render action: 'show', status: :created, location: @chapter }
      else
        format.html { render action: 'new' }
        format.json { render json: @chapter.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /chapters/1
  # PATCH/PUT /chapters/1.json
  def update
    respond_to do |format|
      if @chapter.update(chapter_params)
        format.html { redirect_to book_chapter_path(@book, @chapter), notice: 'Chapter was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @chapter.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /chapter/1
  # PATCH/PUT /chapter/1.json
  def complete
    respond_to do |format|
      if @chapter.complete!
        format.html { redirect_to book_chapters_path(@book), notice: 'Chapter was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { redirect_to book_chapters_path(@book), alert: "Chapter was not completable. Check for the presence of #{LINK_REMOVED_TEXT} in the text" }
        format.json { render json: @chapter.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /chapter/1
  # PATCH/PUT /chapter/1.json
  def uncomplete
    respond_to do |format|
      if @chapter.uncomplete!
        format.html { redirect_to book_chapters_path(@book), notice: 'Chapter was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @chapter.errors, status: :unprocessable_entity }
      end
    end
  end


  # DELETE /chapters/1
  # DELETE /chapters/1.json
  def destroy
    @chapter.destroy
    respond_to do |format|
      format.html { redirect_to book_chapters_path(@book, @chapter) }
      format.json { head :no_content }
    end
  end

  def sort
    all_chapters
    @chapters.each do |chapter|
      chapter.position =  params['chapter'].index(chapter.id.to_s) +1
      chapter.save
    end
    head :ok, :content_type => 'text/html'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_chapter
      @chapter = Chapter.find(params[:id])
      @book = Book.find(params[:book_id])
      authorize @chapter
      authorize @book
    end
    def set_book
      @book = Book.find(params[:book_id])
      authorize @book
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def chapter_params
      params.require(:chapter).permit(:title, :introtext, :fulltext, :death, :ending, :beginning, :book_id, :position)
    end

    def all_chapters
      @chapters = policy_scope(@book.chapters).by_order
    end
end

app/helpers/chapters_helper.rb
module ChaptersHelper
	def shortcode_to_link(chapter, var, replacements)
		field = chapter.send(var)
		chapters_linked = field.scan(/\[#{LINK_REPLACEMENT_TEXT} (\w*)\]/).flatten.uniq
		unless chapters_linked.empty?
			chapters_linked.map do |child_chapter|
			  current_child_chapter = Chapter.find_by_id(child_chapter)
			  if current_child_chapter && current_child_chapter.book == chapter.book
				field = field.gsub(/\[#{LINK_REPLACEMENT_TEXT} #{current_child_chapter.id}\]/, "<a href=\"##{current_child_chapter.id}\">#{replacements.index(current_child_chapter.id)}</a>".html_safe)
			  end
			end
		end
		field.html_safe
	end
end

app/views/chapters/_form.html.haml
= form_for([@book, @chapter], :html => { :multipart => true, :role => "form", :class => "form-horizontal" }) do |f|
 - if @book.errors.any?
  #error_explanation
   %h2
    {pluralize(@chapter.errors.count, "error")} prohibited this book from being saved:
    %ul
     - @chapter.errors.full_messages.each do |msg|
      li= msg

 .field.form-group
  = f.label :title, :class => "col-sm-2 control-label"
  .col-sm-10
   = f.text_field :title, :class => "form-control"

 .field.form-group
  = f.label :introtext, :class => "col-sm-2 control-label"
  .col-sm-10
   = f.text_area :introtext, :class => "form-control redactor-intro", :rows => 40, :cols => 120

 .field.form-group
  = f.label :fulltext, :class => "col-sm-2 control-label"
  .col-sm-10
   = f.text_area :fulltext, :class => "form-control redactor", :rows => 40, :cols => 120

 .field.form-group
  = f.label :death, :class => "col-sm-2 control-label"
  .col-sm-10
   = f.check_box :death, :class => "form-control switch"

 .field.form-group
  = f.label :ending, :class => "col-sm-2 control-label"
  .col-sm-10
   = f.check_box :ending, :class => "form-control switch"

 = f.hidden_field :book_id

 #chapter-list.hidden
  %h3 Select a chapter to link from the list
  = select_tag(:child_chapter, options_for_select(@chapter.book.chapters.collect {|p| [p.title, p.id] if p.id != @chapter.id}.compact), :include_blank => true)

 .actions.form.group
  = f.submit class: 'btn btn-primary'

app/views/chapters/edit.html.haml
.container.chapters
 .row 
  .col-md-12
   %ol.breadcrumb
    %li #{link_to 'Book', book_path(@book) }
    %li #{link_to 'Chapters', book_chapters_path(@book) }
    %li.active=@chapter.title
 .row
  .chapter-list.col-md-12
   .widget-header
    %i.icon-list-alt
    %h3 Editing chapter

   .widget-content
    = render 'form'
   = link_to 'Back', book_chapters_path(@book), :class => "btn btn-default"

app/views/chapters/index.html.haml
:javascript
 $(document).ready(function() {
  $( ".sortable" ).sortable({
   axis: 'y',
   cursor: 'move',
   dropOnEmpty: false,
   opacity: 0.4,
   scroll: true,
   update: function(){
    $.ajax({
       url: '/books/2/chapters/sort',
       type: 'post',
       data: $(this).sortable("serialize", 'id'),
       dataType: 'script',
       complete: function(request){
         $('.chapters').effect('highlight');
       }
     });
   }
  });;
  $( ".sortable" ).disableSelection();
 });

.container.chapters
 .row 
  .col-md-12
   %ol.breadcrumb
    %li #{link_to 'Book', book_path(@book) }
    %li.active Chapters list
 .row
  .chapter-list.col-md-12
   .widget-header
    %i.icon-list-alt
    %h3 Chapters

   .widget-content
    .actions
     = link_to "<span class=\"glyphicon glyphicon-plus\"></span>".html_safe, new_book_chapter_path(@book)
     = link_to "<span class=\"glyphicon glyphicon-map-marker\"></span>".html_safe, book_chapters_map_path(@book), 'data-popup' => true

    %table.table.table-hover.chapters
     %thead
      %tr
       %th
       %th Title
       %th Beginning
       %th Ending
       %th Death
       %th
     %tbody.sortable
      -@chapters.each do |chapter|
       %tr{:id => "chapter_#{chapter.id}"}
        %td
         - if chapter.completed?
          = link_to "<span class=\"label label-success\"><span class=\"glyphicon glyphicon-ok\"></span></span>".html_safe, uncomplete_book_chapter_path(@book, chapter), method: :post, data: { confirm: 'Are you sure?' }
         - else
          = link_to "<span class=\"label label-danger\"><span class=\"glyphicon glyphicon-remove\"></span></span>".html_safe, complete_book_chapter_path(@book, chapter), method: :post, data: { confirm: 'Are you sure? You won\'t be able to edit the chapter until you reopen it again.' }
        %td.ui-state-default
         %span.ui-icon.ui-icon-arrowthick-2-n-s
         - if chapter.completed? 
          = chapter.title
         - else
          = link_to chapter.title, edit_book_chapter_path(@book, chapter) 
        %td
         %span.label{:class => "label-" + (chapter.beginning? ? "success" : "default")}
          %span.glyphicon{:class => "glyphicon-" + (chapter.beginning? ? "ok" : "remove")}
        %td
         %span.label{:class => "label-" + (chapter.ending? ? "success" : "default")}
          %span.glyphicon{:class => "glyphicon-" + (chapter.ending? ? "ok" : "remove")}
        %td
         %span.label{:class => "label-" + (chapter.death? ? "success" : "default")}
          %span.glyphicon{:class => "glyphicon-" + (chapter.death? ? "ok" : "remove")}
        %td
         = link_to "<span class=\"glyphicon glyphicon-trash\"></span>".html_safe, book_chapter_path(@book, chapter), method: :delete, data: { confirm: 'Are you sure?' }
    = link_to "Book details", edit_book_path(@book), :class => "btn btn-default"

app/views/chapters/map.html.erb
<p id="notice"><%= notice %></p>

<svg width="100%" height="600" class="map">
    <g transform="translate(20,20)"/>
</svg>
        <script>
         
         // Create a new directed graph
var g = new dagreD3.Digraph();

// Add nodes to the graph. The first argument is the node id. The second is
// metadata about the node. In this case we're going to add labels to each of
// our nodes.
<%
@chapters.each do |chapter| 
    label = ""
    #label.concat(" - Beginning") if chapter.beginning?
    #label.concat(" - Active") if chapter.completed? 
    #label.concat(" - Death") if chapter.death?
    %>
    g.addNode("<%= chapter.id %>", { label: "<%= chapter.title.concat(label) %>", subtitle: "<%= strip_tags chapter.introtext %>", nodeClass: "<%="active " if chapter.completed? %><%="beginning " if chapter.beginning?%><%="death " if chapter.death?%>" });
<%
end

@chapters.each do |chapter| 
    chapter.parents.each do |parent| 
        label = ""
        
        label.concat("Beginning ") if parent.beginning?
        label.concat("Ending ") if chapter.ending?

        %>
        g.addEdge(null, "<%= parent.id %>", "<%= chapter.id %>", { label: "<%= label %>", nodeClass: "<%="beginning " if parent.beginning? %><%="ending " if chapter.ending? %>" });
    <%
    end
end
%>

var renderer = new dagreD3.Renderer();
renderer.run(g, d3.select("svg g"));
        </script>

<%= link_to 'Back', books_path %>

app/views/chapters/new.html.haml
.container.chapters
 .row 
  .col-md-12
   %ol.breadcrumb
    %li #{link_to 'Book', book_path(@book) }
    %li #{link_to 'Chapters', book_chapters_path(@book) }
    %li.active New
 .row
  .chapter-list.col-md-12
   .widget-header
    %i.icon-list-alt
    %h3 New chapter

   .widget-content
    = render 'form'
   = link_to 'Back', book_chapters_path(@book), :class => "btn btn-default"

app/views/chapters/show.html.haml
%p#notice= notice
%p
 %strong Title:
 = @chapter.title

%p
 %strong Introtext:
= @chapter.introtext.html_safe

%p
 %strong Fulltext:
= @chapter.fulltext.html_safe

= link_to 'Edit', edit_book_chapter_path(@book, @chapter), :class => "btn btn-default"
= link_to 'Back', book_chapters_path(@book), :class => "btn btn-default"