config/routes.rb
Bookgame::Application.routes.draw do

  devise_for :users
  
  resources :users

  resources :books do
   post :complete, on: :member
   post :uncomplete, on: :member
   post :publish, on: :member
   post :unpublish, on: :member
   resources :chapters do
    post :sort, on: :collection
    post :complete, on: :member
    post :uncomplete, on: :member
   end
  end

  match 'user/:id/view' => 'users#view', :via => :get, :as => :user_view

  match 'book/:book_id/chapters/map' => 'chapters#map', :via => :get, :as => :book_chapters_map
  match 'book/:id/view' => 'books#view', :via => :get, :as => :book_view
  match 'book/:id/download' => 'books#download', :via => :get, :as => :book_download

  root 'welcome#index'

end

app/views/layouts/_login.html.haml
- unless user_signed_in?
 %li= link_to "Login", new_user_session_path
 %li= link_to "Sign up", new_user_registration_path
- else
 %li
  = link_to edit_user_registration_path do
   %i.icon-wrench
   Settings
 %li
  = link_to user_view_path(current_user)  do
   %i.icon-wrench
   Public Profile
 %li
  = link_to destroy_user_session_path, :method => "DELETE" do
   %i.icon-off
   Esci

app/views/layouts/_navigation.html.haml
.navbar.navbar-fixed-top.navbar-default{:role => "navigation"}
 .navbar-inner
  .container
   .navbar-header
    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
    %span.sr-only Toggle navigation
    %span.icon-bar
    %span.icon-bar
    %span.icon-bar
    </button>
    %a.navbar-brand{:href => root_path}
     Bookgame
   .navbar-collapse.collapse#main-menu
    %ul.nav.navbar-nav
     - if user_signed_in?
      %li
       = link_to "Books", books_path
     - if user_signed_in? and current_user.admin?
      %li
       = link_to "Users", users_path
    %ul.nav.navbar-nav.pull-right.login
     = render :partial => 'layouts/login'

app/views/layouts/_navigation_headless.html.haml
.navbar.navbar-fixed-top.navbar-default{:role => "navigation"}
 .navbar-inner
  .container
   .navbar-header
    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
    %span.sr-only Toggle navigation
    %span.icon-bar
    %span.icon-bar
    %span.icon-bar
    </button>
    %a.navbar-brand{:href => root_path}
     Bookgame

app/views/layouts/_notifications.html.haml
- if notice
 .alert.alert-success
  %p
   =notice
- if alert
 .alert.alert-warning
  %p
   =alert

app/views/layouts/application.html.haml
!!!
%html
 %head
  %title 
   Bookgame
  = stylesheet_link_tag    "application", :media => "all",  "data-turbolinks-track" => true
  = javascript_include_tag "application", "data-turbolinks-track" => true
  = csrf_meta_tags
  = favicon_link_tag
  <link rel="apple-touch-icon-precomposed" href="apple-touch-icon.png" />
  <link rel="apple-touch-icon-precomposed" sizes="57x57" href="apple-touch-icon-57x57-precomposed.png" />
  <link rel="apple-touch-icon-precomposed" sizes="72x72" href="apple-touch-icon-72x72-precomposed.png" />
  <link rel="apple-touch-icon-precomposed" sizes="114x114" href="apple-touch-icon-114x114-precomposed.png" />

 %body
  = render :partial => 'layouts/navigation'
  .wrapper
   .container
    .row
     .col-md-12.col-sm-12
      = render :partial => 'layouts/notifications'
      = yield

app/views/layouts/headless.html.haml
!!!
%html
 %head
  %title 
   Bookgame
  = stylesheet_link_tag    "application", :media => "all",  "data-turbolinks-track" => true
  = javascript_include_tag "application", "data-turbolinks-track" => true
  = csrf_meta_tags
  = favicon_link_tag
  <link rel="apple-touch-icon-precomposed" href="apple-touch-icon.png" />
  <link rel="apple-touch-icon-precomposed" sizes="57x57" href="apple-touch-icon-57x57-precomposed.png" />
  <link rel="apple-touch-icon-precomposed" sizes="72x72" href="apple-touch-icon-72x72-precomposed.png" />
  <link rel="apple-touch-icon-precomposed" sizes="114x114" href="apple-touch-icon-114x114-precomposed.png" />

 %body
  = render :partial => 'layouts/navigation_headless'
  .wrapper
   .container
    .row
     .col-md-12.col-sm-12
      = render :partial => 'layouts/notifications'
      = yield

app/views/layouts/pdf.html.haml
!!!
%html
 %head
  %title 
   Bookgame
  = stylesheet_link_tag    "application", :media => "all",  "data-turbolinks-track" => true
  = javascript_include_tag "application", "data-turbolinks-track" => true
  = csrf_meta_tags
  = favicon_link_tag
  <link rel="apple-touch-icon-precomposed" href="apple-touch-icon.png" />
  <link rel="apple-touch-icon-precomposed" sizes="57x57" href="apple-touch-icon-57x57-precomposed.png" />
  <link rel="apple-touch-icon-precomposed" sizes="72x72" href="apple-touch-icon-72x72-precomposed.png" />
  <link rel="apple-touch-icon-precomposed" sizes="114x114" href="apple-touch-icon-114x114-precomposed.png" />
  
  = yield :stylesheets
  = wicked_pdf_stylesheet_link_tag "pdf"

 %body
  #header
  #content
   = yield

app/views/layouts/welcome.html.haml
!!!
%html
 %head
  %title 
   Bookgame
  = stylesheet_link_tag    "application", :media => "all",  "data-turbolinks-track" => true
  = javascript_include_tag "application", "data-turbolinks-track" => true
  = csrf_meta_tags
  = favicon_link_tag
  <meta name="viewport" content="width=device-width, initial-scale=1.0"> 
  <link rel="apple-touch-icon-precomposed" href="apple-touch-icon.png" />
  <link rel="apple-touch-icon-precomposed" sizes="57x57" href="apple-touch-icon-57x57-precomposed.png" />
  <link rel="apple-touch-icon-precomposed" sizes="72x72" href="apple-touch-icon-72x72-precomposed.png" />
  <link rel="apple-touch-icon-precomposed" sizes="114x114" href="apple-touch-icon-114x114-precomposed.png" />

 %body.welcome
  .wrapper
   %ul.nav.pull-right.login
    = render :partial => 'layouts/login'
   = yield